name: 🚀 Feature Request
description: Suggest a new feature or enhancement for 1MCP
title: '[Feature]: '
labels: ['enhancement']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide as much detail as possible to help us understand your request.

        **Language:** Please write your request in English to help our global community understand and contribute to the discussion.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission checklist
      description: Please verify these items before submitting your feature request
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I have checked the roadmap and documentation for existing related features
          required: false

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: Provide a clear and concise description of the feature you'd like to see
      placeholder: 'As a user, I want to be able to...'
    validations:
      required: true

  - type: textarea
    id: problem-motivation
    attributes:
      label: Problem/Motivation
      description: What problem does this feature solve? What's the motivation behind this request?
      placeholder: |
        **Current situation:**
        Describe the current limitation or problem.

        **Why this matters:**
        Explain why this feature would be valuable.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: |
        **How it should work:**
        Describe the expected behavior and user experience.

        **Technical considerations:**
        Any thoughts on implementation or technical requirements.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Are there alternative solutions or workarounds you've considered?
      placeholder: "I've considered using X, but it doesn't work because..."
    validations:
      required: false

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Which area of 1MCP does this feature relate to?
      options:
        - MCP Server Management
        - Configuration & Settings
        - CLI Interface & Commands
        - Authentication & Security
        - Logging & Debugging
        - Performance & Optimization
        - Documentation & Help
        - Integration & Compatibility
        - Other (please specify below)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Important for my use case
        - Critical - Blocking my adoption/usage
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        **Example 1:**
        When I do X, I want to be able to Y so that Z.

        **Example 2:**
        In scenario A, this feature would allow me to B.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Any other context or screenshots about the feature request:
        - Mockups or diagrams
        - Related issues or discussions
        - Links to similar features in other tools
        - Any other relevant information
