name: Main

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Trigger CI workflow for testing and validation
  ci:
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read

  # Build binaries (needed for release)
  binaries:
    needs: ci
    uses: ./.github/workflows/binaries.yml
    permissions:
      contents: write

  # Publish to npm (needs binaries for release)
  release:
    needs: [ci, binaries]
    uses: ./.github/workflows/release.yml
    secrets: inherit
    permissions:
      contents: write
      id-token: write

  # Build and publish Docker images
  docker:
    needs: ci
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      security-events: write
