name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'README*'
      - 'CHANGELOG*'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'README*'
      - 'CHANGELOG*'
  workflow_dispatch:
    inputs:
      run_e2e:
        description: 'Run E2E tests'
        required: false
        default: false
        type: boolean
  workflow_call:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HUSKY: 0

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build

      - name: Test Unit
        run: pnpm test:unit

      - name: Test E2E
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.run_e2e == 'true'
        run: pnpm test:e2e
