name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'README*'
      - 'CHANGELOG*'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'README*'
      - 'CHANGELOG*'
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HUSKY: 0

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build

      - name: Test Unit
        run: pnpm test:unit

  # Parallel E2E tests - run automatically on every push/PR
  test-e2e-parallel:
    runs-on: ubuntu-latest
    needs: ci
    strategy:
      matrix:
        shard: [1, 2, 3, 4]
      fail-fast: false
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Build
        run: pnpm build

      - name: Test E2E - Shard ${{ matrix.shard }}/4
        run: |
          # Run E2E tests with sharding for maximum parallelism
          # Each shard runs 1/4 of the tests in parallel
          pnpm test:e2e --shard=${{ matrix.shard }}/4 --reporter=basic
        env:
          CI: true
